osx_image: xcode11
language: objective-c

jobs:
  include:
    - stage: Testing in macos
      script:
      - brew install openssl
      - |
        set -eo pipefail &&
        swift build &&
        vapor test
        
